version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: /home/spider2108/shopapiapp
    command: 'bash -c "sleep 20; until curl -s http://db:5432; do echo ''Waiting for db...''; sleep 2; done; && ./gradlew bootRun"'
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_PASSWORD: shoppass
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shopapi
      SPRING_DATASOURCE_USERNAME: shopuser
    networks:
      - app-network
    ports:
      - published: 8080
        target: 8080
    depends_on:
      - liquibase

  db:
    environment:
      POSTGRES_DB: shopapi
      POSTGRES_PASSWORD: shoppass
      POSTGRES_USER: shopuser
    image: postgres:16
    networks:
      - app-network
    ports:
      - published: 5432
        target: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

  liquibase:
    command: 'bash -c "until pg_isready -h db -p 5432; do echo ''Waiting for db...''; sleep 2; done; liquibase --url=jdbc:postgresql://db:5432/shopapi?autoReconnect=true&useSSL=false --username=shopuser --password=shoppass --changeLogFile=/db/changelog/changelog.yaml update"'
    environment:
      LIQUIBASE_CHANGELOG: /db/changelog/changelog.yaml
      LIQUIBASE_PASSWORD: shoppass
      LIQUIBASE_URL: jdbc:postgresql://db:5432/shopapi?autoReconnect=true&useSSL=false
      LIQUIBASE_USER: shopuser
    image: liquibase/liquibase:latest
    networks:
      - app-network
    volumes:
      - /home/spider2108/shopapiapp/src/main/resources/db/changelog:/db/changelog:rw
    depends_on:
      - db


volumes:
  postgres_data:
