version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shopapi
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  liquibase:
    command: 'bash -c "ls -al; liquibase --url=jdbc:postgresql://db:5432/shopapi --username=shopuser --password=shoppass --changeLogFile=/db/changelog/changelog.yaml update"'
    depends_on:
      - db
    image: liquibase/liquibase:latest
    networks:
      - app-network
    user: root
    volumes:
      - ./src/main/resources/db/changelog:/db/changelog:rw

  app:
    build: .
    command: 'bash -c "sleep 20; ./gradlew bootRun"'
    ports:
      - "8080:8080"
    depends_on:
      - liquibase
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shopapi
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
