openapi: 3.0.2
info:
  title: Shop API
  description: API для магазина
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Локальный сервер

paths:
  /products:
    get:
      summary: Получить список товаров
      operationId: getProducts
      tags:
        - Product
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductDto"

    post:
      summary: Добавить новый товар
      operationId: createProduct
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDto"
      responses:
        "201":
          description: Товар создан

components:
  schemas:
    ProductDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        category:
          type: string
        price:
          type: number
          format: big-decimal
        available_stock:
          type: integer
        supplier_id:
          type: string
          format: uuid
        image:
          $ref: "#/components/schemas/Image"

    Image:
      type: object
      properties:
        id:
          type: string
          format: uuid
        image:
          type: string
          format: byte
