spring:
  datasource:
    url: jdbc:postgresql://db:5433/shopapi
    username: shopuser
    password: shoppass
    driver-class-name: org.postgresql.Driver
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      pool-name: HikariPool-1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    urls:
      - name: My OpenAPI
        url: /openapi.yaml
logging:
  level:
    org.springframework.arm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    "org.hibernate": warn
    "org.hibernate.orm.connections.pooling": warn
    org:
      springframework=ERROR:
    edu:
      school21=ERROR:
