spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopapi
    username: shopuser
    password: shoppass
    driver-class-name: org.postgresql.Driver
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      pool-name: HikariPool-1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    "org.hibernate": warn
    "org.hibernate.orm.connections.pooling": warn
